### ISSUE TITLE
Fix the ACL for Nosto settings 

### ISSUE THREAD

**Issue by hannunosto** [Nosto/nosto-magento#120]
Advanced Nosto settings can not be accessed even though the correct role is set. 

Nosto advanced settings page in admin is not found when accessing settings for the first time. Logout & login is required

**Comment by dannydnz** [comment]
I haven't yet seen an elegant solution for this so would be interested to see one.

Magento loads the ACL into the session when the user logs in. It isn't updated after this. This is standard Magento behaviour and most user who have installed extensions before expect this.

I'd imagine it would be quite tricky to fix this and it would require some core files to be overridden.
I seen some approaches where they override the Mage_Adminhtml_System_ConfigController::_isSectionAllowed and reload it on every request which in my opinion  adds in unnecessary overhead.

**Comment by hannunosto** [comment]
Thanks for the heads up @dannydnz. I'll take a look and see if I can find acceptable solution. It seems we're not the only ones struggling with this issue

**Comment by hannunosto** [comment]
There seems to be no easy way to get around this. Pretty much all plug-ins I've tested are having the same issue.
