### ISSUE TITLE
Overriden Product Data > custom tag is not working > fatal

### ISSUE THREAD

**Issue by tomekjordan** [Nosto/nosto-magento#156]
Hi. I tried to extend Nosto 2.6.5 with My_Nosto custom "minimodule" but when I try to enable it I'm getting fatal on product page. How to fix it?
Thanks
Log:
```
Fatal error: Uncaught Error: Call to a member function loadData() on boolean in
/home/admin/domains/domain.com/public_html/app/code/community/Nosto/Tagging/Block/Product.php:78
Stack trace: #0 /home/admin/domains/domain.com/public_html/app/design/frontend/base/default/template/nostotagging/product.phtml(36): Nosto_Tagging_Block_Product->getMetaProduct() #1 /home/admin/domains/domain.com/public_html/var/cache/ew/files/7a/b0/Mage/Core/Block/Template.php(260): include('/home/admin/dom...') #2 /home/admin/domains/domain.com/public_html/app/code/local/Extendware/EWMinify/Block/Override/Mage/Core/Template.php(29): Mage_Core_Block_TemplateOverriddenClass->fetchView('frontend/base/d...') #3 /home/admin/domains/domain.com/public_html/var/cache/ew/files/7a/b0/Mage/Core/Block/Template.php(291): Extendware_EWMinify_Block_Override_Mage_Core_Template->fetchView('frontend/base/d...') #4 /home/admin/domains/domain.com/public_html/var/cache/ew/files/7a/b0/Mage/Core/Block/Template.php(305): Mage_Core_Block_TemplateOverriddenClass->re in
/home/admin/domains/domain.com/public_html/app/code/community/Nosto/Tagging/Block/Product.php on line 78
```

**Comment by hannunosto** [comment]
Hi @tomekjordan, it seems you are extending Product block when you should be extending product model (https://github.com/Nosto/nosto-magento/blob/develop/app/code/community/Nosto/Tagging/Model/Meta/Product.php). Can you please double check the `config.xml` and make sure you're extending the product model.

**Comment by tomekjordan** [comment]
Hi. I use your instruction and confi.xml rewrite is for
```
<rewrite>
<meta_product>My_Nosto_Model_Meta_Product</meta_product>
</rewrite>
```

is this right?

**Comment by hannunosto** [comment]
Oh, sorry I got a bit confused. Your XML seems ok and you are extending the product model correctly. The issue is in the block (https://github.com/Nosto/nosto-magento/blob/develop/app/code/community/Nosto/Tagging/Block/Product.php#L77). `Mage::getModel('nosto_tagging/meta_product');` seems to be returning boolean for some reason. Can you provide full sources for the "mini module"? If you could create a gist or zip package & make it available for download somewhere?

**Comment by tomekjordan** [comment]
I just use copy paste from your mini module example. but even with your tag value 'nosto' it creates this error. see the code below. I just like to inject dropdown type attribute values, checked all options. but even your $this->_tags['tag3'][] = 'nosto'; is not working


```
            // This can be removed when implementing this extension, it's here only to
            // check that the override works when implemented.
			$this->_tags['tag3'][] = 'nosto';
			//$this->_tags['tag2'][] = $product->getData('kolekcja');
            //$this->_tags['tag3'][] = $product->getAttributeText('kolekcja');
```

**Comment by hannunosto** [comment]
Hey @tomekjordan, without the full source codes of your "mini module" it's really hard to find out what goes wrong. I must also say that extending models, blocks, etc. in Magento requires somewhat deep knowledge about how Magento works and it definitely requires development experience :) Copy pasting is not usually enough, especially when playing around with Magento.

**Comment by tomekjordan** [comment]
HI. I zipped it. its just 2-3 files, the same from your example. but it doesn't work.....
[https://drive.google.com/open?id=0B2fbe9gqQel5NnRVMDhwQmRrVHc](https://drive.google.com/open?id=0B2fbe9gqQel5NnRVMDhwQmRrVHc)

**Comment by hannunosto** [comment]
Hi, the sources look ok to me. As this doesn't seem to be a bug in our code but more of a configuration issue, let's move this conversation to email. Can you please email your contact details to platforms@nosto.com. Include the version of the Magento your using, the plug-in version you are using and the Nosto account id. Thanks!

**Comment by tomekjordan** [comment]
platforms@nosto.com email don't work...or is not allow external communication

Delivery Status Notification (Failure)
We're writing to let you know that the group you tried to contact (platforms) may not exist, or you may not have permission to post messages to the group. A few more details on why you weren't able to post:

 * You might have spelled or formatted the group name incorrectly.
 * The owner of the group may have removed this group.
 * You may need to join the group before receiving permission to post.
 * This group may not be open to posting.

**Comment by tomekjordan** [comment]
BTW: please re-think tagging solution. it would be easy and nice to just have 3 tags to choose in Magento backend and assign Magento product attributes for them. Just give some requirements to handle only dropdown or yes/no and it will be great.

**Comment by hannunosto** [comment]
Hey @tomekjordan, sorry for the email hassle. Please use magento@nosto.com. That allows emails outside our company as well.

We actually just committed yesterday a feature that allows you to add product attributes to tags. Feel free to checkout develop branch and you can test it.

**Comment by tomekjordan** [comment]
That's cool. long waited feature. Should I reindex nosto to obtain those tags inside your panel? BTW: never give plain emails on net or you don't care about spam :)
