### ISSUE TITLE
Zero priced order items, lead to unitPrice being set to an empty string, which raises a PHP warning in NostoHelperPrice.php

### ISSUE THREAD

**Issue by pixelhed** [Nosto/nosto-magento#169]
There is an issue with Nosto_Tagging_Model_Meta_Order_Item which sets the value of Nosto_Tagging_Model_Meta_Order_Item.untiPrice = '' where the order item has a unitPrice of 0.
This in itself then causes a warning to be raised in 

nosto-magento-extension/lib/nosto/php-sdk/src/classes/helper/NostoHelperPrice.php:50

The empty string is passed to the helper and the php function number_format() complains:

`Warning: number_format() expects parameter 1 to be double, string given in {PATH_TO_MAGENTO}.modman/nosto-magento-extension/lib/nosto/php-sdk/src/classes/helper/NostoHelperPrice.php on line 50
`
The reason why this occurs is because of the check here:
https://github.com/Nosto/nosto-magento/blob/develop/app/code/community/Nosto/Tagging/Model/Meta/Order/Item.php#L107

` if (!isset($args['unitPrice']) || empty($args['unitPrice'])) {`
 
as the order item has a zero price

`empty($args['unitPrice']` returns true, this in turn sets the value of 

`$args['unitPrice'] = '';`

and this is the source of the error.

Is this behaviour intended?

**Comment by hannunosto** [comment]
@pixelhed thanks for reporting this and sorry for the delay in getting back to you. I moved this issue to the SDK side (https://github.com/Nosto/php-sdk/issues/32).
