### ISSUE TITLE
Exit intent - sensivity

### ISSUE THREAD

**Issue by tomekjordan** [Nosto/nosto-magento#189]
Hi. I noticed that exit intent triggers to fast. Its opened just when user moves cursor outsite browser window. Its not good because every user moves accidentaly outsite browser window. Because it gives discount each time - it means lower margins > almost each user gets discount. Not good for business. In many cases user moves cursor by accident, and get back to window right away > it means we don't need to share discounts for it so fast.

I saw solution for it: to adjust sensivity (screen move outsite area VS time to be outsite of the window).
So it may trigger if user moves cursor for 100px outside for not less than 2s. Sensivity levels could be done just like Optinin Monster app does [http://prntscr.com/d1vz9e](http://prntscr.com/d1vz9e)
Something similar uses Sumome for their exit popups.

High sensitivity will cause the optin to be triggered when the visitor’s mouse is further away from the browser, than a Medium or Low sensitivity setting would.

Each setting correlates to a specific pixel value. When the visitor is that many pixels away from the top of the browser window with their mouse, the optin will be triggered to appear. The pixel value for each setting is as follows:

Low: 1 pixel
Medium: 50 pixels
High: 150 pixels

Thanks for considering this thing

Tomek

**Comment by hannunosto** [comment]
Hey @tomekjordan, thanks for your feedback, that is a very valid point! I talked with our dev team and they agreed that this would be a good addition to the rules for triggering popups. We have added this into our backlog.

Currently the merchants can already define the delay / wait for popups to appear.  

I'm closing the issue from this repo as this is not related to our Magento extension but core Nosto functionalities.
