### ISSUE TITLE
Customer - Nosto Customer Reference

### ISSUE THREAD

**Issue by zarapico** [Nosto/nosto-magento#190]
In file https://github.com/Nosto/nosto-magento/blob/develop/app/code/community/Nosto/Tagging/Helper/Setup.php#L65

input => 'label'

the type does not exist in magento, which causes an error when editing a user from the backoffice and try to save changes

**Comment by hannunosto** [comment]
Thanks for reporting this @zarapico, good catch! I rolled out a fix where I the input type is changed to text. The fix is is merged to master and develop branches and is also available in Magento connect.
