### ISSUE TITLE
Support for MAP pricing

### ISSUE THREAD

**Issue by davis2125** [Nosto/nosto-magento#192]
Currently any product that has MAP pricing enabled only shows the MSRP price instead of Click For Price, Show Price, etc. 

Example below shows a product that has MAP enabled and should be showing Click for Price but is only showing the MSRP price.

![nosto](https://cloud.githubusercontent.com/assets/14129105/19981501/32ad5dc2-a1d0-11e6-9c02-5ad24fbe264b.JPG)

**Comment by hannunosto** [comment]
Hey @davis2125, you have a very valid point here. There are few ways to handle MAP in Nosto recommendations. Here are two options that should be quite easy and straight forward.

1. Using product attributes
Without any customisations to the plug-in you can choose to add MAP related attributes to Nosto tags. "Product attributes to tags" is a feature we introduced in 2.7.0 (https://github.com/Nosto/nosto-magento/releases/tag/2.7.0). Once you have MAP related attributes added into Nosto tags you can implement the logic of not showing the prices in Nosto recommendation templates (https://support.nosto.com/manuals/building-recommendation-templates/). If you don't want to recommend products with MAP it's also possible blacklist products in Nosto that have MAP tags.

2. Overriding / extending the Nosto product model
This method requires a bit coding. The basics of the product overriding can be found from here https://github.com/Nosto/nosto-prestashop/wiki/Modifying-Product-Data. After you have your "mini extension" in place you should define the product to be invisible or out of stock if MAP is effective. This way Nosto would not recommend products that have "Click for price" in Magento.
