### ISSUE TITLE
Dispatch Event for Custom Product Data

### ISSUE THREAD

**Issue by sprankhub** [Nosto/nosto-magento#205]
Could you please dispatch an event in [Nosto_Tagging_Model_Meta_Product::loadData](https://github.com/Nosto/nosto-magento/blob/develop/app/code/community/Nosto/Tagging/Model/Meta/Product.php#L153), so that we can add custom product data via an event observer rather using a rewrite? This is much cleaner. If you implement it, the [wiki](https://github.com/Nosto/nosto-magento/wiki/Overriding-Product-Data) should be updated as well.

**Comment by hannunosto** [comment]
Thanks for the idea @sprankhub. We will add this into some of out releases in near future
