### ISSUE TITLE
lib directory is missing for composer install

### ISSUE THREAD

**Issue by tylerssn** [Nosto/nosto-magento#241]

**Comment by hannunosto** [comment]
Hey @tylerssn, the lib directory should be created automatically by the composer. Or maybe I'm missing something here. Can you elaborate?

**Comment by tylerssn** [comment]
I've since installed Nosto using an alternative method. But if I remember correctly, I was getting an error because the extension was looking for data in Magento's lib directory but the composer package was not creating it. Generally there is something like this in the composer.json of Magento 1 packages that create the lib dir:

```
    "type": "magento-module",
    "extra": {
        "map": [
            ["lib/package-location", "src/lib/package-location"],
        ]
    }
```

**Comment by hannunosto** [comment]
Hi, when installing the plug-in from the sources the module itself nor the composer creates lib directory inside Magento installation. The extension and composer are not really aware of Magento installation path. You might want to check the instructions how to deploy / install extension via modman (https://github.com/Nosto/nosto-magento/wiki#modman)
