### ISSUE TITLE
Avoid loading products from database if using product API is turned off on new order

### ISSUE THREAD

**Issue by oostman** [Nosto/nosto-magento#256]
If I understand it correctly we do get product from the order in $order->getPurchasedItems();
https://github.com/Nosto/nosto-magento/blob/b3f814874ab1a8a25f1c84fb6085f7599c1974db/app/code/community/Nosto/Tagging/Model/Service/Order.php#L85

**Comment by hannunosto** [comment]
This is handled with feature flags in version 3.0.0
