### ISSUE TITLE
Performance Issues

### ISSUE THREAD

**Issue by sprankhub** [Nosto/nosto-magento#296]
I just did some profiling and encountered that the Nosto extension has a significant performance footprint on the product page. I kind of broke it down into the root cause:

1. The template `app/design/frontend/base/default/template/nostotagging/product.phtml` is slow (approx. 240ms on my local machine). Cause:
2. The method `Nosto_Tagging_Block_Product::getMetaProduct` is slow. Cause:
3. The method `Nosto_Tagging_Model_Meta_Product::loadData` is slow. Cause:
4. The method `Nosto_Tagging_Model_Meta_Product::buildCategories` is slow (still approx. 150ms). Cause:
5. The method `Nosto_Tagging_Helper_Data::buildCategoryString` is slow.

As you can see, `buildCategories` is not the only slow method in `Nosto_Tagging_Model_Meta_Product::loadData` - but the slowest one. Could you please have a look at that? I think there are two TODOs:

1. Check if there is any way to improve the performance of `Nosto_Tagging_Model_Meta_Product::loadData`. E.g. is it really necessary to load all parent categories?
2. Implement a cache for all Nosto blocks if possible.

**Comment by hannunosto** [comment]
Thanks for reporting this @sprankhub and sorry for the prolonged reply. We do indeed need the parent categories for Nosto products but we will have closer look if we can improve the performance of the category building.

**Comment by sprankhub** [comment]
Thanks for your feedback. What is the current status?

**Comment by sprankhub** [comment]
...?

**Comment by hannunosto** [comment]
Sorry again for the delay getting back to this. We are looking into adding a custom indexer to speedup the product loading in near future. Unfortunately at this point I cannot promise more detailed schedule for custom indexer implementation.

**Comment by sprankhub** [comment]
Sorry, but I have to bump this again. Every day, this is slowing down clients websites and leading to a worse conversion rate. You really have to solve this issue!

**Comment by hannunosto** [comment]
We are currently working on indexer implementation https://github.com/Nosto/nosto-magento/tree/experiment/custom-indexer. As the branch name suggests this is still somewhat experimental feature

**Comment by hannunosto** [comment]
Nosto indexer is now available as a pre-release version here: https://github.com/Nosto/nosto-magento/releases/tag/3.4.0-RC1. Nosto product is saved in the database so there's only one db lookup for Nosto product on product page.

We also recommend full page caching if the load time for product page (or any other page) gets too high.
