### ISSUE TITLE
Not installable: "modman" file contains references to non-existing directories

### ISSUE THREAD

**Issue by siment** [Nosto/nosto-magento#309]
Your **modman** files contains references to the following locations:

```
lib/Nosto  lib/Nosto
lib/Dotenv  lib/Dotenv
```

Those directories do not exist and will break module installation when using deploy strategy from
[magento-hackathon/magento-composer-installer](https://github.com/Cotya/magento-composer-installer). (A very common deploy strategy plugin for Magento 1 installations using Composer packages)

Error output:

```bash
$ composer require nosto/nosto-magento-extension:"~3.3"
# <!-- SNIP --> #
Installation failed, reverting ./composer.json to its original content.

                                                                                                                          
  [ErrorException]                                                                                                        
  Source /var/www/vendor/nosto/nosto-magento-extension/lib/Nosto does not exists
# <!-- SNIP --> #
```

**Comment by chenliangde** [comment]
@siment The lib/Nosto and lib/Dotenv are generated by phing build.  https://github.com/Nosto/nosto-magento/blob/develop/build.xml#L80

And their are available in the output package file.
https://github.com/Nosto/nosto-magento/releases/download/3.3.0/Nosto_Tagging-3.3.0.tgz
