### ISSUE TITLE
lib/nosto -> lib/Nosto

### ISSUE THREAD

**Issue by magefast** [Nosto/nosto-magento#352]
Hi,

Server return error 500 

seen some bugs with name of directory lib/nosto .

Need only rename directory to lib/nosto -> lib/Nosto
And update file app/code/community/Nosto/Tagging/bootstrap.php ,
change /nosto/php-sdk/src/config.inc.php to /Nosto/php-sdk/src/config.inc.php

And works :)

**Comment by hannunosto** [comment]
Hi @magefast, can you elaborate the issue you are having? Nosto's lib directory should be automatically `lib/Nosto` after you run `/vendor/bin/pearify`. The `config.inc.php` was also removed from our PHP SDK (https://github.com/Nosto/nosto-php-sdk) in 3.0.0. Perhaps you forgot to run `composer install` after checking out this repo? Can you please try to do a fresh install following these instructions https://github.com/Nosto/nosto-magento/wiki/Installing#installing-via-modman and let us know if you come across any issues.
