### ISSUE TITLE
Send list of smart categories to nosto

### ISSUE THREAD

**Issue by chenliangde** [Nosto/nosto-magento#366]
Some of the categories are created with smart rules to select associated products. Send all of these categories to nosto so that them could be excluded from being used

**Comment by hannunosto** [comment]
Development notes
* Add a feature flag for sending navigational categories to Nosto or not
* Add categories that have rules as an array to the settings payload that is sent to Nosto

**Comment by hannunosto** [comment]
This has not been requested recently. We will re-open if needed
