### ISSUE TITLE
Possibility to install nosto via composer

### ISSUE THREAD

**Issue by bjoern-flagbit** [Nosto/nosto-magento#386]
Hey Nosto-Devs,

can you maybe provide the possibility to install nosto-magento via composer?

At the moment the problem is that the nosto-sdk is not found where it should be, during installation.
`vendor/nosto/nosto-magento-extension/lib/`

Greetings
Björn

**Comment by bjoern-flagbit** [comment]
One problem is that the autoloader is throwing an error because of:
`/lib/nosto/* does not exist`

So you need to install the lib via:
`/vendor/bin/pearify process`

Or you do composer install in the module repository and commit the lib.

A really easy solution is to tell php-sdk another installation dir instead of vendor see:
https://getcomposer.org/doc/faqs/how-do-i-install-a-package-to-a-custom-path-for-my-framework.md

**Comment by hannunosto** [comment]
Hey @bjoern-flagbit, Magento doesn't natively support installing extensions via composer and the biggest challenge is the transitive dependencies ([Nosto PHP SDK] (https://github.com/Nosto/nosto-php-sdk) in this case) and Magento's autoloader. We decided to go with [pearify](https://github.com/mridang/pearify) that makes it possible to autoload our PHP SDK classes by renaming the classes in PHP SDK and placing them into the `lib` directory.

Please have a look [how to use modman](https://github.com/Nosto/nosto-magento/wiki/Installing#installing-via-modman) for installing Nosto extension. Alternative option is to [use a fork of this repo](https://github.com/Nosto/nosto-magento-nodeps) that doesn't have transitive dependencies.
