### ISSUE TITLE
OVerriding product data: merchant reports we have updated the documentation and and the old version doesn't work

### ISSUE THREAD

**Issue by StanislavKraus** [Nosto/nosto-magento#411]
" * Example 1" on this page is different from what we used to have in the past. see below.
https://github.com/Nosto/nosto-magento/wiki/Overriding-Product-Data
1. can you confirm that the new use is correct? What is the exact reason we changed it?
2. do you see relevance to send out a mailing? Everyone with overridden product data and a custom mini-plugin for this might have an issue now.

old version - from merchant:

* Example 1
         *
         * Adding "tag2" and "tag3" properties.
         *
         * These properties are used to include more information about the
         * product that can in turn be used for more granular control in the
         * product recommendations.
         *
         * The format of "tag2" and "tag3" is an array containing string values.
         *
         * If you have a custom attribute (string value) stored in the Magento
         * product model, it can be added to a tag field like this:
         *
         * $this->_tags['tag2'][] = $product->getData('my_custom_attribute');
         *
         * Or by fetching the attribute text:
         *

         *
         * If you have values stored in a custom model that are linked to the
         * product, you could do something like this:
         *
         * $this->_tags['tag2'] = Mage::getModel('my_extension/model')->getProductAttributes($product);
         */
//        $this->_tags['tag2'] = array('example1', 'example2');
//        $this->_tags['tag3'] = array('example3');

**Comment by supercid** [comment]
The example is correct. If he is using an older version of the plugin, maybe lookup for past revisions of this wiki article:
https://github.com/Nosto/nosto-magento/wiki/Overriding-Product-Data/_history
And more specifically:
https://github.com/Nosto/nosto-magento/wiki/Overriding-Product-Data/98b7dfa76fe4a9ebe28e8b7dd9859a2a882bf52a
