### ISSUE TITLE
Missing pagetype

### ISSUE THREAD

**Issue by jitheesh-lumi** [Nosto/nosto-magento#415]
Nosto is reporting missing page type and this is because of following code.
$this->getPageTypeName() is always returns page type value. 
`$this->getPageTypeName() !== null` will always true, so page type template won't be added to front end html.
https://github.com/Nosto/nosto-magento/blob/caae2616c004e89040be0f173380f801cbd82e47/app/code/community/Nosto/Tagging/Block/Pagetype.php#L55

**Comment by supercid** [comment]
Hi @jitheesh-lumi, thanks for pointing out. We've just rolled out a fix for it. 😀
