### ISSUE TITLE
Mage_Customer_Exception If Customer Data Is Sent To Nosto

### ISSUE THREAD

**Issue by sprankhub** [Nosto/nosto-magento#418]
If `nosto_tagging/general/send_customer_data` is activated, you get tons of exceptions in your `exception.log`:

    2018-07-09T12:09:32+00:00 ERR (3): Got exception Mage_Customer_Exception with message: Customer email is required, error code: 0)

Reason: In `Nosto_Tagging_Block_Customer::getCustomerReference`, you try to save the customer even though the customer is not logged in and has therefore no mail address.

Workaround: Disable `nosto_tagging/general/send_customer_data`.

**Comment by supercid** [comment]
@sprankhub 
Thanks for reporting this bug! We have now released a new version with a fix.
You can download in:
https://github.com/Nosto/nosto-magento/releases/tag/3.7.2
