### ISSUE TITLE
Add type checks for blocks that use HTML serialization

### ISSUE THREAD

**Issue by hannunosto** [Nosto/nosto-magento#426]
All blocks (cart, product, order, etc.) that use direct HTML rendering must check that object can be rendered. For example here https://github.com/Nosto/nosto-magento/blob/develop/app/code/community/Nosto/Tagging/Block/Order.php#L56 `$this->getOrder()` could return `null`

**Comment by hannunosto** [comment]
This might get fixed with #427

**Comment by supercid** [comment]
Already fixed.
