### ISSUE TITLE
Nosto is loading all the parent products when we save one of the child ones, causing a permissions issue

### ISSUE THREAD

**Issue by arnau-hortelano** [Nosto/nosto-magento#444]
**Information:**

- Magento Enterprise Edition 1.14.3.9
- Magento with multiple websites and store views
- Admin users in a Role with restricted access to some web sites
- Nosto module v3.7.4

When we save a simple product child of some configurables, Nosto is loading all the parent configurable products (event catalog_product_save_commit_after). If the current admin user have restricted access to specific web sites and one of this configurable products exist only in one of the restricted website, Magento throws the error "Not enough permissions to view this item." fired by the Enterprise_AdminGws core module.

Possible related commit: https://github.com/Nosto/nosto-magento/commit/b3bab031ae301ddd2e86b0ba8b50541547a9434c

**Exception log**
> 2018-10-25T10:42:38+01:00 ERR (3): 
exception 'Enterprise_AdminGws_Controller_Exception' with message 'Not enough permissions to view this item.' in /app/Mage.php:580
Stack trace:
#0 /app/code/core/Enterprise/AdminGws/Model/Models.php(1200): Mage::exception('Enterprise_Admi...', 'Not enough perm...')
#1 /app/code/core/Enterprise/AdminGws/Model/Models.php(240): Enterprise_AdminGws_Model_Models->_throwLoad()
#2 /app/code/core/Enterprise/AdminGws/Model/Observer.php(580): Enterprise_AdminGws_Model_Models->catalogProductLoadAfter(Object(Mage_Catalog_Model_Product))
#3 /app/code/core/Enterprise/AdminGws/Model/Observer.php(382): Enterprise_AdminGws_Model_Observer->_invokeCallback('catalogProductL...', 'enterprise_admi...', Object(Mage_Catalog_Model_Product))
#4 /app/code/core/Mage/Core/Model/App.php(1358): Enterprise_AdminGws_Model_Observer->validateModelLoadAfter(Object(Varien_Event_Observer))
#5 /app/code/core/Mage/Core/Model/App.php(1337): Mage_Core_Model_App->_callObserverMethod(Object(Enterprise_AdminGws_Model_Observer), 'validateModelLo...', Object(Varien_Event_Observer))
#6 /app/Mage.php(448): Mage_Core_Model_App->dispatchEvent('model_load_afte...', Array)
#7 /app/code/core/Mage/Core/Model/Abstract.php(266): Mage::dispatchEvent('model_load_afte...', Array)
#8 /app/code/core/Mage/Catalog/Model/Product.php(596): Mage_Core_Model_Abstract->_afterLoad()
#9 /app/code/core/Mage/Core/Model/Abstract.php(226): Mage_Catalog_Model_Product->_afterLoad()
#10 /app/code/community/Nosto/Tagging/Util/Product.php(90): Mage_Core_Model_Abstract->load('10503')
#11 /app/code/community/Nosto/Tagging/Model/Service/Product.php(76): Nosto_Tagging_Util_Product::toParentProducts(Object(Mage_Catalog_Model_Product))
#12 /app/code/community/Nosto/Tagging/Model/Service/Product.php(162): Nosto_Tagging_Model_Service_Product->update(Array)
#13 /app/code/community/Nosto/Tagging/Model/Observer/Product.php(67): Nosto_Tagging_Model_Service_Product->updateProduct(Object(Mage_Catalog_Model_Product))
#14 /app/code/core/Mage/Core/Model/App.php(1358): Nosto_Tagging_Model_Observer_Product->sendProductUpdate(Object(Varien_Event_Observer))
#15 /app/code/core/Mage/Core/Model/App.php(1337): Mage_Core_Model_App->_callObserverMethod(Object(Nosto_Tagging_Model_Observer_Product), 'sendProductUpda...', Object(Varien_Event_Observer))
#16 /app/Mage.php(448): Mage_Core_Model_App->dispatchEvent('catalog_product...', Array)

KR.

**Comment by hannunosto** [comment]
Thanks for reporting this @arnau-hortelano. We will have a look. I cannot promise super quick fix for this one but we'll keep you posted.

**Comment by arnau-hortelano** [comment]
Hello again @hannunosto and thanks for your quick response! do you know what will happen if I just disable (for example returning an empty array) the function toParentProducts extending your module as a temporal patch?

**Comment by hannunosto** [comment]
Hi @arnau-hortelano, I wouldn't alter the `Nosto/Tagging/Util/Product::toParentProducts`. That would prevent some product updates to go through and it might break the product handling in other ways as well. You can disable the API calls (https://github.com/Nosto/nosto-magento/wiki/Configuring#advanced-settings) for now. We will provide a fix within the next upcoming weeks.

**Comment by arnau-hortelano** [comment]
I've tried to disable the API calls but I'm still having this same error, this time from the Nosto_Tagging_Model_Indexer_Product Class:

```
...
#10 app/code/community/Nosto/Tagging/Util/Product.php(78): Mage_Core_Model_Abstract->load('18799')
#11 app/code/community/Nosto/Tagging/Model/Indexer/Product.php(226): Nosto_Tagging_Util_Product::toParentProducts(Object(Mage_Catalog_Model_Product))
#12 app/code/community/Nosto/Tagging/Model/Indexer/Product.php(212): Nosto_Tagging_Model_Indexer_Product->addProductToIndexQueue(Object(Mage_Catalog_Model_Product))
#13 app/code/core/Mage/Index/Model/Indexer/Abstract.php(89): Nosto_Tagging_Model_Indexer_Product->_registerEvent(Object(Mage_Index_Model_Event))
#14 app/code/core/Mage/Index/Model/Process.php(141): Mage_Index_Model_Indexer_Abstract->register(Object(Mage_Index_Model_Event))
#15 [internal function]: Mage_Index_Model_Process->register(Object(Mage_Index_Model_Event))
...
```
Thank you very much for the support!

**Comment by hannunosto** [comment]
Hi @arnau-hortelano, let's take your case via Nosto's support. We most likely need to exchange some login credentials to have a temporary resolution for your store.

**Comment by supercid** [comment]
Hi @arnau-hortelano, we have just released a fix for this issue!
Feel free to update your plugin version and thanks again for reporting this 😃 .
https://github.com/Nosto/nosto-magento/releases/tag/3.7.6
