### ISSUE TITLE
Add how to remove Nosto from a storefront (how to uninstall)

### ISSUE THREAD

**Issue by StanislavKraus** [Nosto/nosto-magento#451]
Add a section on how to remove Nosto from a storefront. There is a view in Magento, but also in the Nosto UI. Clarify what it does and how to do it. Helpful when the same account is used for staging and production environment.
Suggestion, could be added here: 
https://github.com/Nosto/nosto-magento/wiki/Installing

**Comment by supercid** [comment]
Here we have a new article about disconnecting nosto from your storefront:
https://github.com/Nosto/nosto-magento/wiki/Disconnecting-Nosto-From-Store-Front
