### ISSUE TITLE
Article on how to uninstall the plugin

### ISSUE THREAD

**Issue by mridang** [Nosto/nosto-magento#463]
I think we need to a top-level article that explains how to uninstall the module. This article should explain how to do it via the UI i.e. Magento Connect Manager and the CLI i.e. `mage`

**Comment by supercid** [comment]
- [ ]  Add section about how remove the module via CLI using `mage` command
- [ ]  Add section about removing the module using Magento Connect Manager

**Comment by mridang** [comment]
https://github.com/Nosto/nosto-magento/wiki/Uninstalling
