### ISSUE TITLE
Send additional metadata through headers with all API calls

### ISSUE THREAD

**Issue by mridang** [Nosto/nosto-magento#48]
We could send headers with all API calls to Nosto. `X-Plugin-Version`, `X-Platform-Version`, and `X-Platform-Name`

**Comment by kryysler** [comment]
I would use more specific name. Non-standards X-headers are widely used, and more generic names tend to collide easier. Even if X-headers are no longer encouraged by IETF (http://tools.ietf.org/html/rfc6648), custom headers that will never be standardised will continue to use the X-prefix

**Comment by kryysler** [comment]
I'm not sure we wan't to include this in the 3.0.0 release, at it will be a while before it's going to be released, i.e. probably Q1 2016.
