### ISSUE TITLE
Errors With Enriched Customer Tagging -  Undefined offset: 1 in Customer.php on Line 122

### ISSUE THREAD

**Issue by mindfriction** [Nosto/nosto-magento#480]
Hello,

After updated to the latest version 3.8.2, I get the following errors in Magento:

Notice: Undefined offset: 1  in /html/app/code/community/Nosto/Tagging/Block/Customer.php on line 122

Line 122: $nostoCustomer->setStreet($customerAddress->getStreet()[0].' '.$customerAddress->getStreet()[1]);

**Comment by mridang** [comment]
@mindfriction What version of Magento are you running BTW?

**Comment by mindfriction** [comment]
Hi @mridang 
I'm running v 1.9.4.0

**Comment by hannunosto** [comment]
Thanks for reporting @mindfriction. We will add a nullcheck to this in the next release. It should be released within a few days.

**Comment by hannunosto** [comment]
@mindfriction the fix is out https://github.com/Nosto/nosto-magento/releases/tag/3.8.3. Please comment here if the issue is not solved in 3.8.3
