### ISSUE TITLE
Class 'Nosto_Object_PageType' not found'

### ISSUE THREAD

**Issue by oleksandr-sumtsov** [Nosto/nosto-magento#489]
Hello.
We are getting this
Class 'Nosto_Object_PageType' not found'

I think it is because of it \Nosto_Tagging_Block_Pagetype::_toHtml

**Comment by hannunosto** [comment]
@oleksandr-sumtsov I'm afraid you need to elaborate a bit. Can you post the full stack trace? Also, how did you install the Nosto extension? `Nosto_Object_PageType` is a class in our PHP SDK so you are using modman you need to install the SDK via composer and possibly run the pearify as well. Here are the details: https://github.com/Nosto/nosto-magento/wiki/Installing#installing-via-modman

**Comment by mridang** [comment]
I think this issue has been handled via support. It was due to missing dependencies in your installation.
