### ISSUE TITLE
On reindex: Uncaught Error: Class 'Nosto_Helper_UrlHelper' not found

### ISSUE THREAD

**Issue by hardiklinksture** [Nosto/nosto-magento#514]
Same issue with #504 

I copy and past all file in magento root directory

Nosto Ver. 3.10.0

```
Fatal error: Uncaught Error: Call to undefined method Nosto_Tagging_Helper_UrlHelper::parseDomain() in /app/code/community/Nosto/Tagging/Helper/Url.php:488 Stack trace: 
#0 /app/code/community/Nosto/Tagging/Model/Service/Product.php(195): Nosto_Tagging_Helper_Url->getActiveDomain(Object(Mage_Core_Model_Store)) 
#1 /app/code/community/Nosto/Tagging/Model/Indexer/Product.php(579): Nosto_Tagging_Model_Service_Product->updateOutOfSyncToNosto() 
#2 /app/code/core/Mage/Index/Model/Process.php(212): Nosto_Tagging_Model_Indexer_Product->reindexAll() 
#3 /app/code/core/Mage/Index/Model/Process.php(260): Mage_Index_Model_Process->reindexAll() 
#4 /app/code/community/Nosto/Tagging/Helper/Url.php on line 488
```

**Comment by supercid** [comment]
Hi @hardiklinksture,
Please don't copy the files manually. We have a wiki tutorial about how to install the plugin.
Refer to the wiki here:
https://github.com/Nosto/nosto-magento/wiki/Installing

**Comment by hardiklinksture** [comment]
i follow the step : Installing via Modman
if i try command **modman init** then it will showing error below

`modman: command not found`
Can you please guide here.
https://prnt.sc/nh3xp7

**Comment by hannunosto** [comment]
Installing and using modman is out of the scope our extension. Please refer to https://github.com/colinmollenhour/modman#installation

**Comment by hardiklinksture** [comment]
Thanks for installation step but now we face Permission denied (publickey) issue can you please check 
https://prnt.sc/nh4vsl

**Comment by hannunosto** [comment]
That error is again out of scope if the extension. Please, only report issues if you find something is not working in our extension.
