### ISSUE TITLE
Bundle prices are not calculated properly during indexing for stores with non-default currency

### ISSUE THREAD

**Issue by souserge** [Nosto/nosto-magento#518]
The problem seems to be similar to #465 but with regard to bundle prices. The problem is that e.g. for bundle products in the prices for a Polish store are calculated in euro (as in other stores) rather than in PLN.

**Comment by hannunosto** [comment]
Can you please elaborate. We would need your Magento version, Nosto extension version & steps to reproduce the issue. Thanks!

**Comment by souserge** [comment]
Magento ver. 1.9.3.6
Nosto extension 3.10.0

Steps to reproduce: 
1. Create two store views
2. Set a currency different to the default one for the last store view created
3. Create a couple of products to be bundled and set different prices (in their respective currencies) for the store views
4. Create a bundle product with a dynamic price and add created products to it
4. Enable indexing for the Nosto extension
6. After indexing, observe that the serialised bundle product in `nosto_tagging_index` for the second store view has prices from taken from the first store view

**Comment by hannunosto** [comment]
Thanks @souserge, we'll give it a shot

**Comment by hannunosto** [comment]
We could not reproduce this with a standard installation. We'll take this via our support since it seems to be some sort of configuration related issue. We'll reopen if this turns out to be a bug

**Comment by souserge** [comment]
Can you also try to run such a script?
```
$productId = 1111; // Id of a bundle product with a dynamic price set up in several store views with different prices
$products = Mage::getModel('nosto_tagging/product')
    ->getCollection()
    ->addAttributeToSelect('*')
    ->addIdFilter(array($productId));

Mage::getModel('nosto_tagging/indexer_product')->reindexAndUpdateMany($products);
```
For me it's always the case that the product in subsequent stores has prices taken from the first store that was reindexed. When I run the reindex for one store only, the problem does not occur.
