### ISSUE TITLE
Magento v1 and shopify incognito - frontpage nosto recommendations not show

### ISSUE THREAD

**Issue by gitty8** [Nosto/nosto-magento#533]
**Magento version(s) used**: 1.9.3.1
**Extension version(s) affected**: 3.8.4

**How to reproduce**  

Run magento store with Nosto 3.8.4 and frontpage nosto recommendations in Google Chrome Incognito. Sometimes on Mobile Chrome 75.0.3770.143 frontpage Nosto recommendations not show up too. 

Unfortunately, I can't name the Live Store, but it also applies to Shopify Stores.
Maybe a developer can reproduce this and find the bug?

**Comment by supercid** [comment]
Hi @gitty8,
This is not related to our extension. Please visit our support center and open a ticket on https://www.nosto.com/support/ and they will take it from there.
