### ISSUE TITLE
PHP Deprecated:  Non-static method

### ISSUE THREAD

**Issue by mindfriction** [Nosto/nosto-magento#540]
**Magento version(s) used**: 1.9.4.0 / PHP v7.2
**Extension version(s) affected**: 3.11.3

**Description** 
PHP Deprecated:  Non-static method Nosto_Tagging_Helper_Log::logWithMemoryConsumption() should not be called statically
/app/code/community/Nosto/Tagging/Model/Service/Product.php on line 249

**Possible Solution**  
Make the function logWithMemoryConsumption() static
/app/code/community/Nosto/Tagging/Helper/Log.php
on Line 97

**Comment by olsi-qose** [comment]
The method is not used anymore and removed.
