### ISSUE TITLE
Add M1 ATC function without page reload (via AJAX)

### ISSUE THREAD

**Issue by StanislavKraus** [Nosto/nosto-magento#545]
Problem:
After clicking an "add to cart" button in the shop frontend" a page reload is performed, which is unwelcome here, since the shop's own function doesn't perform a reload.

Desired Solution:
Add items to cart after button-click without a page reload.

What we have tried:
We have tried to replicate the shop's function of adding items without a reload. It doesn't work.

This feature is economical decisive for the merchant to stay with us or not.

**Comment by hannunosto** [comment]
We can only support the standard / built-in add to cart functionality. When custom logic or 3rd party plugins are used for cart management Nosto's add to cart functionality must be customized as well by the merchant / agency.
