### ISSUE TITLE
Cookie compilance GDPR

### ISSUE THREAD

**Issue by ClickCons** [Nosto/nosto-magento#557]
I wanted to tell you that we have discovered a bug in your plugin for Magento version 4.1.0.
We managed to disable the initialization of nosto by Javascript (as marked by your article http://help.nosto.com/en/articles/1811603-how-can-website-visitors-opt-out-of-cookies-and-data-collected-and-processed-by-nosto), however a nosto cookie was being created at the time of adding to the cart (nosto.itemsAddedToCart).
This cookie is generated by PHP through your module.
We have solved the problem by adding a conditional to the file: app / code / community / Nosto / Tagging / Model / Observer / Cart.php
Specifically towards line 97:

                if($cookie->get('nostojs')){

                    $cookie->set(
                        self::COOKIE_NAME,
                        Nosto_Helper_SerializationHelper::serialize($cartUpdate),
                        60,     //60 seconds
                        '/',    //path
                        false,
                        false,
                        false
                    );
                    
                }

Could you confirm if our solution is correct and if you can add it to your next release?
Thank you.

**Comment by hannunosto** [comment]
Thanks for reporting @ClickCons. We'll test this in near future and let you know .

**Comment by fairlane** [comment]
@ClickCons thanks for this one. This is now implemented in version [4.1.1](https://github.com/Nosto/nosto-magento/releases/tag/4.1.1)
