### ISSUE TITLE
Indexer not found exception after upgrade from version 3.* to 4.*

### ISSUE THREAD

**Issue by spinsch** [Nosto/nosto-magento#560]
**Magento version(s) used**: OpenMage LTS 1.9.4.x
**Extension version(s) affected**: 3.6.1

**Description**  
Magento throws an exception in the Backend because the Nosto Indexer still registers in the database after the update but the file is no longer present.

**How to reproduce**  
Install extension version 3.6.1 and then make an upgrade to latest release

**Possible Solution**  
Remove nosto indexer from database table ```index_process```

_edited: fixed version_

**Comment by fairlane** [comment]
Hi @spinsch thanks for reporting this. Could you please describe the exact steps how to reproduce the issue?

**Comment by spinsch** [comment]
hi @hannunosto
sorry for not answering for so long.

i found the problem with magento myself. if you disable the magento cache before updating, there are no problems. 

**To answer your question:**
I had all Magento caches active and replaced the extension in version 3.6.1 with the newest one (files).
After the first request in the backend the error occurred.
Because in config.xml the indexer was deleted but the cache was still active, Magento threw an error because it still registered the indexer in the cache but did not have the files anymore.

**Comment by fairlane** [comment]
Ok @spinsch thanks for getting back to this. I'm closing this for now. We'll reopen if needed.
